server:
  port: ${FLOODIT_SERVER_PORT:5000}

spring:
  datasource:
    url: jdbc:postgresql://${FLOODIT_DATABASE_HOST:localhost}:${FLOODIT_DATABASE_PORT:5432}/${FLOODIT_DATABASE_NAME:floodit}
    username: ${FLOODIT_DATABASE_USERNAME:floodit}
    password: ${FLOODIT_DATABASE_PASSWORD}
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
