
    create table games (
        board_height integer not null,
        board_width integer not null,
        max_moves integer not null,
        number_of_colors integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        seed bigint not null,
        updated_at timestamp(6) not null,
        version bigint not null,
        player_name varchar(255) not null,
        secret varchar(255) not null,
        state varchar(255) not null check (state in ('ONGOING','WIN','LOSS')),
        primary key (id)
    );

    create table moves (
        color integer not null,
        created_at timestamp(6) not null,
        game_id bigint not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    alter table if exists moves 
       add constraint game_id_fkey 
       foreign key (game_id) 
       references games;
